### ISSUE TITLE
The required library libhostfxr.so could not be found.

### ISSUE THREAD

**Issue by alexdresko** [tmds/Tmds.DBus#100]
I'm on a ras pi 4 running the latest raspbian lite, and I only have the .NET 5 SDK installed. When I run `dotnet-dbus`, I get this:

```
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/pi/.dotnet/tools/.store/tmds.dbus.tool/0.9.1/tmds.dbus.tool/0.9.1/tools/netcoreapp3.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm&rid=raspbian.10-arm&apphost_version=5.0.4
```

It _could_ be that I botched the SDK installation, but everything else seems to work fine.

**Comment by tmds** [comment]
Fixed by https://github.com/tmds/Tmds.DBus/pull/106.

**Comment by stmu01** [comment]
I used this version hope that solves my problem - but still the same (I’m trying since weeks)

Im not able to register a pairing agent that bluez calls it if I execute device.PairAsync()

Pls. Can you short describe how to do that in .net 5.0

thank you for helping
